import Head from 'next/head'
import {Header} from '../lib/header'
import {Footer} from '../lib/footer'
import {Overlay} from '../lib/overlay'
import {Index} from '../lib/index'


export default function Home() {
    return (
        <div className="root">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Header></Header>
            <Overlay></Overlay>

            <main>
                <Index></Index>
            </main>

            <Footer/>
        </div>
    )
}
